services:
  waf:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: BS-WAF
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      start_period: 2s
      retries: 3
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # - ./nginx-waf/modsecurity.conf:/etc/nginx/modsecurity.conf
      - ./nginx-waf/nginx.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./nginx-waf/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
    networks:
      - backend
  db:
    image: postgres:18.3-alpine3.23
    container_name: BS-Postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
      # volumes:
      # - postgres_data:/var/lib/postgresql/data

  app:
    image: buddy-szponter-backend:latest
    # container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: BS-Backend
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/v1/system/health']
      start_period: 3s
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
      - cache
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      VALKEY_URL: valkey://default:${VALKEY_PASSWORD}@cache:6379/0
      MINIO_ENDPOINT: http://simple-storage:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      SALT: ${SALT}
      PEPPER: ${PEPPER}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      DEVELOPMENT: ${DEVELOPMENT} # true or false
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_ENCRYPTED: ${PAYLOAD_ENCRYPTED} # true or false

  cache:
    image: valkey/valkey:9-alpine3.22
    container_name: BS-CacheValkey
    restart: unless-stopped
    environment:
      VALKEY_PASSWORD: ${VALKEY_PASSWORD}
      VALKEY_USER: ${VALKEY_USER}
    command: valkey-server --requirepass ${VALKEY_PASSWORD} --loglevel verbose
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD-SHELL', 'valkey-cli --no-auth-warning -a "$$VALKEY_PASSWORD" -h 127.0.0.1 ping | grep -q PONG']
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  simple-storage:
    image: minio/minio:latest
    container_name: BS-MinIO
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      start_period: 2s
      retries: 3
    networks:
      - backend
    entrypoint: >
      sh -c " /usr/bin/minio server /data --console-address ':9001' &

      echo '⏳ Waiting for MinIO to start...'; until curl -s http://localhost:9000/minio/health/live >/dev/null; do
        sleep 1;
      done

      echo '✅ MinIO is ready. Setting up buckets...'; 

      mc alias set simplestorage http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; 

      mc mb simplestorage/photos || true; mc anonymous set download simplestorage/photos || true;

      mc mb simplestorage/locales || true; mc anonymous set download simplestorage/locales || true;

      echo '✅ Buckets initialized.'; sleep 2s; wait "

  prometheus:
    image: prom/prometheus:latest
    container_name: BS-Prometheus
    profiles:
      - "monitoring"
    restart: unless-stopped
    command: >
      --web.enable-admin-api
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: BS-Grafana
    profiles:
      - "monitoring"
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      start_period: 2s
      retries: 3
    ports:
      - "3001:3000"
    networks:
      - backend
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    command:
      - --nginx.scrape-uri=http://waf:8080/nginx_status
    profiles:
      - "monitoring"
    depends_on:
      - prometheus
      - waf
    ports:
      - "9113:9113"
    networks:
      - backend
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - prometheus
    profiles:
      - "monitoring"
      - db
    networks:
      - backend
  redis-exporter:
    image: oliver006/redis_exporter
    depends_on:
      - prometheus
      - cache
    profiles:
      - "monitoring"
    environment:
      REDIS_ADDR: "cache:6379"
      REDIS_PASSWORD: ${VALKEY_PASSWORD}
    ports:
      - "9121:9121"
    networks:
      - backend

networks:
  backend:
    driver: bridge

# volumes:
#   postgres_data:
